namespace OperationsManager.Models.Enums
{
    public enum Operation
    {

        REGISTER_APPLICATION,
        ADD_APPLICATION_VERSION,


        CREATE_MODULE,
        UPDATE_MODULE,
        MODULE_ADD_CONTEXT,
        MODULE_DELETE_CONTEXT,
        UPDATE_MODULE_TO_VERSION,
        UPDATE_MODULE_TO_CONTEXT,
        DELETE_MODULE,

        CREATE_PATIENT,
        UPDATE_PATIENT,
        DELETE_PATIENT,
        PATIENT_ADD_EXISTING_MODULE,
        PATIENT_NEW_MODULE,
        PATIENT_MODULE_ADD_CONTEXT,
        PATIENT_MODULE_DELETE_CONTEXT,
        UPDATE_PATIENT_MODULE,
        UPDATE_PATIENT_MODULE_TO_VERSION,
        UPDATE_PATIENT_MODULE_CONTEXT,
        DELETE_PATIENT_MODULE,
        PATIENT_REQUEST_THERAPIST,
        PATIENT_REJECT_THERAPIST,

        CREATE_THERAPIST,
        UPDATE_THERAPIST,
        DELETE_THERAPIST,
        THERAPIST_ACCEPT_PATIENT,
        THERAPIST_REJECT_PATIENT,
    }
}
