namespace OperationsManager.Models.Enums
{
    public enum Operation
    {

        REGISTER_APPLICATION,
        ADD_APPLICATION_VERSION,
        UPDATE_APPLICATION_VERSION,
        DELETE_APPLICATION_VERSION,
        DELETE_APPLICATION,


        CREATE_MODULE,
        UPDATE_MODULE,
        UPDATE_MODULE_TO_VERSION,
        UPDATE_MODULE_VERSION,
        DELETE_MODULE,

        CREATE_PATIENT,
        UPDATE_PATIENT,
        DELETE_PATIENT,
        ADD_PATIENT_EXISTING_MODULE,
        ADD_PATIENT_NEW_MODULE,
        UPDATE_PATIENT_MODULE,
        UPDATE_PATIENT_MODULE_VERSION,
        DELETE_PATIENT_MODULE,
        PATIENT_REQUEST_THERAPIST,
        PATIENT_REJECT_THERAPIST,

        CREATE_THERAPIST,
        UPDATE_THERAPIST,
        DELETE_THERAPIST,
        THERAPIST_ACCEPT_PATIENT,
        THERAPIST_REJECT_PATIENT,
    }
}
